### ISSUE TITLE
taiga-back fails to start

### ISSUE THREAD

**Issue by sesceu** [kalumkalac/docker-taiga-back#1]
Hello,
I'm getting connection issues, when the frontend tries to connect to the backend. When I "docker exec" into the taiga-back container and look at the gunicorn.stderr logs in /usr/local/taiga/logs, I can see that the worker is unable to boot. Manually running the fix from [here](https://github.com/taigaio/taiga-back/issues/832) seems to fix the problem. Maybe this should be part of your startup script?

**Comment by DeLoWaN** [comment]
Hi,

I've run into the same issue when building the image but already fixed it. See this commit: 0e0013ecddbb817679d033ec15366ed9c01bef8e. 
Maybe you ran on old version of the image ? The current '[latest](https://hub.docker.com/r/kalumkalac/taiga-back/builds/bzdm5hmyjh8pghxfzkredlf/)' tag is correctly using the right version of taiga slack plugin. Check out the build details.

**Comment by sesceu** [comment]
Yes, it's running now. Thanks.
